FROM --platform=linux/x86_64 ubuntu:23.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install -y --no-install-recommends\
                    vim \
                    git \
                    gcc-13 \
                    g++-13 \
                    build-essential \
                    cmake \
                    unzip \
                    tar \
                    ca-certificates \
                    wget \
                    pipx


# Install C++ dep manager conan
RUN pipx ensurepath && pipx install conan==2.0.13

# Not available yet
#RUN apt-get install -y --no-install-recommends openjdk-21

# Install Java-21 
ADD https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz .
RUN tar -xvf jdk-21_linux-x64_bin.tar.gz \
    && cd jdk-21.0.1 \
    && mkdir -p /usr/local/jdk-21 \
    && mv * /usr/local/jdk-21 \
    && export JAVA_HOME=/usr/local/jdk-21 \
    && export PATH=$JAVA_HOME/bin:$PATH

RUN /bin/bash -c "source ~/.bashrc"

RUN echo 'export JAVA_HOME=/usr/local/jdk-21' >> ~/.bashrc \
    && echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc

RUN /bin/bash -c "source ~/.bashrc"

#RUN java --version  && echo $JAVA_HOME

